### ISSUE TITLE
Deleting / updating metafields errors out - CSRF token

### ISSUE THREAD

**Issue by patrickbolle** [husseyexplores/poshify-utilities#10]
`Unable to save changes. (CSRF token is missing. Consider opening an issue in the github repo if you see this error again and agian.)`

Any ideas here? Tried re-installing the extension, no go. This is on the Firefox addon, for reference.

**Comment by husseyexplores** [comment]
I've just tried this and seems to be working.

Can you try logging out of the Shopify store and log back in? Multiple people have had this error and was resolved by doing this.

Let me know this resolves for you or not. If not, then please also let me know if this error is occurring on all resources or just a few? (product/collection/shop/order etc)

**Comment by patrickbolle** [comment]
Seems to work when I have full account access, but not when I only have limited permissions (like just for Products & Apps for example).

Same error for all resources on limited permissions store via Collaborator account.

Logging out and logging back in does not work unfortunately.

Let me know how else I can help!

**Comment by leapin13** [comment]
Having the same issues as patrickbolle
Can't do any changes as CSRF token is missing. Tried on Firefox and Chrome, also tried out to log out and in several times but it still won't work.
Any ideas what it could be?

**Comment by leapin13** [comment]
@husseyexplores could you please look into this and help me out? I really need this extension for my job.
Thanks!

**Comment by husseyexplores** [comment]
@leapin13 I've checked it on multiple stores, and it's working fine.
A few questions:
1. Do you have full access to the store? If not, you may try requesting articles/pages access and try again.
2. Did you try using it at any other store? 
3. Does the extension load? If yes, then which metafield resource you're trying to edit? i.e product, variant, collection, etc

**Comment by leapin13** [comment]
@husseyexplores 
1. it's strange since my colleagues have the same limited access as me and their Poshify works just fine. I probably won't get full access to be honest as this is only for a handful of people (founders for e.g). But as said, all my other colleagues have no issues at all.
2. No as we are only using it for that one store currently
3. Yes, the extension functions just fine until I click the button "Update/Save" . I'm trying to edit collection pages

Thanks!

**Comment by husseyexplores** [comment]
Try getting `articles` access at least and see if that works.

CSRF token is not available on every admin page. So, internally, the extension makes a call to `/admin/articles` and gets the required token from this page. Maybe that's where it's failing for you.
At the end of the day, Shopify can change their code anytime and the extension may stop working. CSRF token is just an example.

**Comment by husseyexplores** [comment]
@leapin13 You can try running this code in the browser dev tools (on the Shopify backend) and see if it works.
```js
// Monkey patching CSRF from different routes
(() => {
  const getHtml = url => fetch(url, {
      "headers": {
        "accept": "text/html, application/xhtml+xml, application/xml",
        "accept-language": "en-US,en;q=0.9",
        "x-shopify-web": "1"
      },
      "method": "GET",
      "credentials": "include"
    })
    .then(r => {
      if (r.ok) {
        return r.text()
      }
      throw new Error('Status Code: ' + r.status)
    })


  const makeDocFromText = htmlText => {
    const parser = new DOMParser()
    const doc = parser.parseFromString(htmlText, "text/html")
    return doc
  }

  const findTokenFromDoc = doc => {
    const csrfMeta = doc.querySelector('meta[name=csrf-token')
    const token = csrfMeta && csrfMeta.getAttribute('content')
    return token || null
  }

  const addTokenToDocument = token => {
    const meta = document.createElement('meta')
    meta.setAttribute('name', 'csrf-token')
    meta.setAttribute('content', token)
    document.body.appendChild(meta);
  }

  async function csrfMonkeyPatch() {
    const possibleCsrfUrls = [
      '/admin/themes',
      '/admin/articles',
      '/admin/collections',
      '/admin/orders',
    ];
    let token = null

    for (let url of possibleCsrfUrls) {
      try {
        token = await getHtml(url)
          .then(makeDocFromText)
          .then(findTokenFromDoc)
        if (token) break;
      } catch(e) {
          console.warn(`Error on path: ${url}: `, e.message)
      }
    }

    if (!token) {
      console.log('Unable to find the token any of these paths: \n', possibleCsrfUrls.join('\n') )
      return
    }

    addTokenToDocument(token)
    console.log('Successfully patched the token!')
  }
  csrfMonkeyPatch();
})()
```
If the above code works, then you'd see the `Successfully patched the token!` message in the console.

Let me know if it works or not. If it does, then you'd need to run this code every time you refresh the page.
